'use client';
import { useEffect, useState } from 'react';
import { FolderKanban, Check, X, Mail, RefreshCw, AlertTriangle, Trash2 } from 'lucide-react';

type Candidate = { id: string; name: string; description: string; company: string; why: string; source: { meeting_id?: string; meeting_title?: string; meeting_date?: string; path?: string; source_url?: string }; people: string[]; objectives: string[]; deadline?: string; owner?: string; confidence: number; status: string };
type Member = { id: string; name: string; role?: string; email?: string };
type Project = { id: string; name: string; company: string; status: string; progress: number; team_members: Member[]; last_update?: string; blockers?: string[]; risks?: string[]; description: string };

const card = 'rounded-2xl border border-border-color bg-bg-secondary p-5 shadow-sm';

function formatDate(value: string) {
  if (!value) return 'Unknown date';
  return new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
}

export default function Projects() {
  const [selectedDate, setSelectedDate] = useState('');
  const [availableDates, setAvailableDates] = useState<string[]>([]);
  const [candidates, setCandidates] = useState<Candidate[]>([]), [projects, setProjects] = useState<Project[]>([]), [members, setMembers] = useState<Member[]>([]);
  const [selected, setSelected] = useState<Record<string, boolean>>({});
  const [notify, setNotify] = useState(false);
  const [confirming, setConfirming] = useState<Candidate | null>(null);
  const [removing, setRemoving] = useState<Project | null>(null);
  const [removalName, setRemovalName] = useState('');
  const [transcript, setTranscript] = useState<{ title: string; date?: string; path?: string; content: string } | null>(null);
  const [transcriptLoading, setTranscriptLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = async (date = selectedDate) => { setError(null); try { const query = date ? `?selected_date=${encodeURIComponent(date)}` : ''; const [p, m] = await Promise.all([fetch(`/api/projects${query}`, { cache: 'no-store' }), fetch('/api/projects/team-members', { cache: 'no-store' })]); if (!p.ok || !m.ok) throw new Error('Projects data is unavailable'); const pd = await p.json(), md = await m.json(); setAvailableDates(pd.available_dates || []); setCandidates((pd.candidates || []).filter((x: Candidate) => x.status === 'pending_confirmation')); setProjects(pd.projects || []); setMembers(md.members || []); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load projects'); } };
  useEffect(() => { load(''); }, []);
  const handleDateChange = async (date: string) => {
    setSelectedDate(date);
    await load(date);
  };
  const viewTranscript = async (candidate: Candidate) => {
    setTranscriptLoading(true);
    setError(null);
    try {
      const response = await fetch(`/api/projects/candidates/${encodeURIComponent(candidate.id)}/transcript`, { cache: 'no-store' });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.detail || payload.error || 'Transcript unavailable');
      setTranscript(payload);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Transcript unavailable');
    } finally {
      setTranscriptLoading(false);
    }
  };
  const act = async (url: string, options?: RequestInit) => { setBusy(true); setError(null); try { const r = await fetch(url, options); if (!r.ok) throw new Error((await r.json().catch(() => null))?.detail || 'Project action failed'); await load(selectedDate); } catch (e) { setError(e instanceof Error ? e.message : 'Project action failed'); } finally { setBusy(false); } };
  const confirm = async () => { if (!confirming || !Object.values(selected).some(Boolean)) { setError('Select at least one authenticated team member.'); return; } await act(`/api/projects/candidates/${confirming.id}/confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ member_ids: Object.keys(selected).filter(k => selected[k]), notify }) }); setConfirming(null); setSelected({}); setNotify(false); };
  const remove = async () => { if (!removing || removalName !== removing.name) { setError('Type the exact project name to confirm deletion.'); return; } await act(`/api/projects?project_id=${encodeURIComponent(removing.id)}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirmation_name: removalName }) }); setRemoving(null); setRemovalName(''); };
  return <div className="flex flex-col gap-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold text-text-primary flex items-center gap-2"><FolderKanban className="w-5 h-5 text-gold" /> Projects</h1><p className="text-xs text-text-muted mt-1">Evidence-backed project detection and tracking. Nothing is created without your confirmation.</p></div><div className="flex items-center gap-2"><label className="flex items-center gap-2 text-xs text-text-muted">Meeting date<select value={selectedDate} onChange={(e) => handleDateChange(e.target.value)} className="rounded-lg border border-border-color bg-bg-secondary px-2.5 py-2 text-xs text-text-primary"><option value="">All dates</option>{availableDates.map((date) => <option key={date} value={date}>{formatDate(date)}</option>)}</select></label><button onClick={() => load()} className="rounded-lg border border-border-color p-2 text-text-secondary hover:text-gold" aria-label="Refresh projects"><RefreshCw className="w-4 h-4" /></button></div></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red">{error}</div>}
    <section className={card}><h2 className="text-sm font-semibold uppercase tracking-wide text-gold">Active Projects <span className="text-text-muted normal-case">({projects.length})</span></h2><div className="mt-4 grid gap-3">{projects.length === 0 ? <p className="text-sm text-text-muted">No confirmed projects yet.</p> : projects.map(p => <article key={p.id} className="rounded-xl border border-border-color bg-bg-card p-4"><div className="flex justify-between"><div><h3 className="font-semibold text-text-primary">{p.name}</h3><p className="text-xs text-text-muted">{p.company} · {p.team_members?.length || 0} team members</p></div><div className="flex items-start gap-3"><span className="text-xs font-semibold text-text-secondary">{p.status}</span><button type="button" disabled={busy} onClick={() => { setRemoving(p); setRemovalName(''); }} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red hover:bg-red-50"><Trash2 className="h-3 w-3" />Remove</button></div></div><div className="mt-3 h-2 rounded-full bg-bg-secondary"><div className="h-2 rounded-full bg-gold" style={{ width: `${p.progress || 0}%` }} /></div><p className="mt-2 text-xs text-text-muted">{p.progress || 0}% · Last update {p.last_update ? new Date(p.last_update).toLocaleString() : 'none'}</p>{p.blockers?.length ? <p className="mt-2 text-xs text-red"><AlertTriangle className="inline w-3 h-3 mr-1" />{p.blockers[0]}</p> : null}</article>)}</div></section>
    <section className={card}><h2 className="text-sm font-semibold uppercase tracking-wide text-gold">Possible Projects <span className="text-text-muted normal-case">({candidates.length})</span></h2><div className="mt-4 grid gap-3">{candidates.length === 0 ? <p className="text-sm text-text-muted">No new project candidates detected from the available transcripts.</p> : candidates.map(c => <article key={c.id} className="rounded-xl border border-border-color bg-bg-card p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-text-primary">{c.name}</h3><p className="text-xs text-text-muted mt-1">{c.source.meeting_title || 'Meeting transcript'} · {c.source.meeting_date || 'Date unknown'} · {c.company}</p></div><span className="text-xs font-semibold text-gold">{Math.round(c.confidence * 100)}% confidence</span></div><p className="text-sm text-text-secondary mt-3">{c.description}</p><p className="text-xs text-text-muted mt-2"><b>Why:</b> {c.why}</p><p className="text-xs text-text-muted mt-2"><b>People:</b> {c.people.join(', ') || 'None captured'} {c.deadline && <> · <b>Deadline:</b> {c.deadline}</>}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={transcriptLoading} onClick={() => viewTranscript(c)} className="rounded-lg border border-border-color px-3 py-2 text-xs font-semibold text-text-secondary hover:text-gold">{transcriptLoading ? 'Loading transcript…' : 'View Meeting Transcript'}</button><button disabled={busy} onClick={() => setConfirming(c)} className="rounded-lg bg-gold px-3 py-2 text-xs font-semibold text-white"><Check className="inline w-3 h-3 mr-1" />Confirm Project</button><button disabled={busy} onClick={() => act(`/api/projects/candidates/${c.id}/dismiss`, { method: 'POST' })} className="rounded-lg border border-border-color px-3 py-2 text-xs font-semibold text-text-secondary"><X className="inline w-3 h-3 mr-1" />Dismiss</button></div></article>)}</div></section>
    {transcript && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="transcript-title"><div className="flex max-h-[85vh] w-full max-w-3xl flex-col rounded-2xl border border-border-color bg-bg-primary shadow-2xl"><div className="flex items-start justify-between border-b border-border-color p-5"><div><h2 id="transcript-title" className="text-lg font-bold text-text-primary">{transcript.title}</h2><p className="mt-1 text-xs text-text-muted">{transcript.date || 'Date unknown'} · {transcript.path || 'Source transcript'}</p></div><button onClick={() => setTranscript(null)} className="rounded-lg border border-border-color px-3 py-2 text-sm text-text-secondary hover:text-gold" aria-label="Close transcript">Close</button></div><pre className="overflow-y-auto whitespace-pre-wrap p-5 text-sm leading-6 text-text-secondary">{transcript.content}</pre></div></div>}
    {removing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true"><div className={`${card} w-full max-w-lg`}><h2 className="text-lg font-bold text-text-primary">Remove project?</h2><p className="mt-2 text-sm text-text-secondary">This permanently removes the active project. Type the exact project name to confirm:</p><p className="mt-3 rounded-lg bg-bg-card p-3 text-sm font-semibold text-text-primary">{removing.name}</p><input autoFocus value={removalName} onChange={e => setRemovalName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') remove(); }} placeholder="Type project name" className="mt-3 w-full rounded-lg border border-border-color bg-bg-primary px-3 py-2 text-sm text-text-primary" /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => { setRemoving(null); setRemovalName(''); }} className="rounded-lg border border-border-color px-3 py-2 text-sm">Cancel</button><button type="button" disabled={busy || removalName !== removing.name} onClick={remove} className="rounded-lg bg-red px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Removing…' : 'Remove Project'}</button></div></div></div>}
    {confirming && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><div className={`${card} w-full max-w-lg`}><h2 className="text-lg font-bold text-text-primary">Select Project Team</h2><p className="text-sm text-text-secondary mt-1">Only authenticated team members are available.</p><div className="mt-4 max-h-64 overflow-y-auto space-y-2">{members.map(m => <label key={m.id} className="flex items-center gap-3 rounded-lg border border-border-color p-3"><input type="checkbox" checked={!!selected[m.id]} onChange={e => setSelected(s => ({ ...s, [m.id]: e.target.checked }))} /><span className="text-sm text-text-primary">{m.name}</span><span className="ml-auto text-xs text-text-muted">{m.role}</span></label>)}</div><label className="mt-4 flex items-center gap-2 text-sm text-text-secondary"><input type="checkbox" checked={notify} onChange={e => setNotify(e.target.checked)} /><Mail className="w-4 h-4 text-gold" />Inform them through Email</label>{notify && <p className="mt-2 text-xs text-text-muted">Hermes will send one generated email only to selected members with authenticated email addresses.</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={() => setConfirming(null)} className="rounded-lg border border-border-color px-3 py-2 text-sm">Cancel</button><button disabled={busy} onClick={confirm} className="rounded-lg bg-gold px-3 py-2 text-sm font-semibold text-white">{busy ? 'Creating…' : 'Create Project'}</button></div></div></div>}
  </div>;
}
